name: faps
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - autopage==0.5.2
      - beautifulsoup4==4.12.3
      - blessed==1.20.0
      - blis==0.7.11
      - boto3==1.34.122
      - botocore==1.34.122
      - catalogue==2.0.10
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cliff==4.7.0
      - cloudpathlib==0.18.1
      - cloudpickle==3.0.0
      - cmaes==0.10.0
      - cmake==3.25.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - confection==0.1.5
      - contourpy==1.2.1
      - croniter==1.3.15
      - cycler==0.12.1
      - cymem==2.0.8
      - dask==2024.5.2
      - dask-expr==1.1.2
      - dateutils==0.6.12
      - decorator==5.1.1
      - deepdiff==7.0.1
      - distributed==2024.5.2
      - docker-pycreds==0.4.0
      - editor==1.6.6
      - executing==2.0.1
      - fastai==2.7.15
      - fastapi==0.88.0
      - fastcore==1.5.45
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.13.1
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - h11==0.14.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - idna==3.4
      - imbalanced-learn==0.12.3
      - importlib-metadata==7.1.0
      - inquirer==3.2.4
      - ipyplot==1.1.1
      - ipython==8.25.0
      - itables==1.5.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - langcodes==3.4.0
      - language-data==1.2.0
      - lightning==2.0.3
      - lightning-cloud==0.5.69
      - lightning-utilities==0.11.2
      - lit==15.0.7
      - llvmlite==0.42.0
      - locket==1.0.0
      - mako==1.3.5
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - murmurhash==1.0.10
      - networkx==3.2.1
      - numba==0.59.1
      - numpy==1.26.3
      - omegaconf==2.3.0
      - optuna==2.10.1
      - ordered-set==4.1.0
      - packaging==24.0
      - pandas==2.0.2
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.6
      - pbr==6.0.0
      - pexpect==4.9.0
      - pillow==9.5.0
      - plotly==5.15.0
      - preshed==3.0.9
      - prettytable==3.10.0
      - prompt-toolkit==3.0.46
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pydantic==1.10.15
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyrootutils==1.0.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.5
      - pyts==0.13.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - readchar==4.1.0
      - requests==2.28.1
      - rich==13.4.2
      - runs==1.2.2
      - s3transfer==0.10.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.30
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.22.0
      - starsessions==1.3.0
      - statsmodels==0.14.2
      - stevedore==5.2.0
      - stumpy==1.12.0
      - sympy==1.12
      - tblib==3.0.0
      - tenacity==8.3.0
      - thinc==8.2.4
      - threadpoolctl==3.5.0
      - toolz==0.12.1
      - torchmetrics==1.4.0.post0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - triton==2.0.0
      - tsai==0.3.8
      - tsfresh==0.20.1
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==1.26.13
      - uvicorn==0.30.1
      - wandb==0.16.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - wrapt==1.16.0
      - xlsxwriter==3.1.8
      - xmod==1.8.1
      - yarl==1.9.4
      - zict==3.0.0
      - zipp==3.19.2
