name: unimodal_image_resnet18

program: src/train.py

project: ai-faps-project

method: bayes

metric:
  name: val/f1_best
  goal: maximize

parameters:
  # RandomGaussianNoise
  data.train_transforms.transforms.2.std:
    distribution: uniform
    min: 0.0
    max: 0.5
  # Gaussian Blur
  data.train_transforms.transforms.3.transforms.0.kernel_size:
    values: [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]
  model.optimizer._target_:
    values: [torch.optim.Adam, torch.optim.AdamW, torch.optim.SGD]
  model.optimizer.lr:
    distribution: uniform
    min: 0.000001
    max: 0.01
  data.batch_size:
    values: [4, 8, 16, 32]
  model.modal_nets.images.unfreeze_layer_count:
    distribution: int_uniform
    min: 1
    max: 52

early_terminate:
  type: hyperband
  eta: 2
  min_iter: 5

command:
  - ${interpreter}
  - ${program}
  - experiment=unimodal/image/resnet18
  - ${args_no_hyphens}
  - trainer=gpu
  - logger=wandb